name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  OKTETO_HOST: ${{ secrets.OKTETO_HOST }}
  OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: lanf0rd
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create images
        run: |
          docker build ./lab5/Flights/ -t lanf0rd/lanf0rdrep:flight
          docker build ./lab5/Bonuses/ -t lanf0rd/lanf0rdrep:bonus
          docker build ./lab5/Tickets/ -t lanf0rd/lanf0rdrep:ticket
          docker build ./lab5/Gateway/ -t lanf0rd/lanf0rdrep:gateway
      - name: Push images
        run: |
          docker push lanf0rd/lanf0rdrep:flight
          docker push lanf0rd/lanf0rdrep:bonus
          docker push lanf0rd/lanf0rdrep:ticket
          docker push lanf0rd/lanf0rdrep:gateway
      - name: Deploy
        run: |
          kubectl config set-cluster rsoi-cluster --server="$OKTETO_HOST" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$OKTETO_TOKEN"
          kubectl config set-context default --cluster=rsoi-cluster --user=cloud_okteto_com-user --namespace="lanf0rd"
          kubectl config use-context default
          helm delete services
          sleep 10
          helm install services ./k8s/services-chart
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"